import os

FAILURE_THRESHOLD = int(os.environ.get("FAILURE_THRESHOLD", 3))
MAX_RESTART_ATTEMPTS = int(os.environ.get("MAX_RESTART_ATTEMPTS", 3))
RESPONSE_TIME_WARNING_MS = int(os.environ.get("RESPONSE_TIME_WARNING_MS", 500))
RESPONSE_TIME_CRITICAL_MS = int(os.environ.get("RESPONSE_TIME_CRITICAL_MS", 2000))
POLL_INTERVAL_SECONDS = int(os.environ.get("POLL_INTERVAL_SECONDS", 5))
ALERT_WINDOW_SECONDS = int(os.environ.get("ALERT_WINDOW_SECONDS", 60))